declare namespace JSX {
  type Element = HTMLElement &
    HTMLAnchorElement &
    HTMLAppletElement &
    HTMLAreaElement &
    HTMLAudioElement &
    HTMLBaseElement &
    HTMLBaseFontElement &
    HTMLQuoteElement &
    HTMLBodyElement &
    HTMLBRElement &
    HTMLButtonElement &
    HTMLCanvasElement &
    HTMLTableCaptionElement &
    HTMLTableColElement &
    HTMLTableColElement &
    HTMLDataElement &
    HTMLDataListElement &
    HTMLModElement &
    HTMLDetailsElement &
    HTMLDialogElement &
    HTMLDirectoryElement &
    HTMLDivElement &
    HTMLDListElement &
    HTMLEmbedElement &
    HTMLFieldSetElement &
    HTMLFontElement &
    HTMLFormElement &
    HTMLFrameElement &
    HTMLFrameSetElement &
    HTMLHeadingElement &
    HTMLHeadElement &
    HTMLHRElement &
    HTMLIFrameElement &
    HTMLImageElement &
    HTMLInputElement &
    HTMLModElement &
    HTMLLabelElement &
    HTMLLegendElement &
    HTMLLIElement &
    HTMLLinkElement &
    HTMLMapElement &
    HTMLMarqueeElement &
    HTMLMenuElement &
    HTMLMetaElement &
    HTMLMeterElement &
    HTMLObjectElement &
    HTMLOListElement &
    HTMLOptGroupElement &
    HTMLOptionElement &
    HTMLOutputElement &
    HTMLParagraphElement &
    HTMLParamElement &
    HTMLPictureElement &
    HTMLPreElement &
    HTMLProgressElement &
    HTMLQuoteElement &
    HTMLScriptElement &
    HTMLSelectElement &
    HTMLSlotElement &
    HTMLSourceElement &
    HTMLSpanElement &
    HTMLStyleElement &
    HTMLTableElement &
    HTMLTableSectionElement &
    HTMLTableDataCellElement &
    HTMLTemplateElement &
    HTMLTextAreaElement &
    HTMLTableSectionElement &
    HTMLTableHeaderCellElement &
    HTMLTableSectionElement &
    HTMLTimeElement &
    HTMLTitleElement &
    HTMLTableRowElement &
    HTMLTrackElement &
    HTMLUListElement &
    HTMLVideoElement &
    SVGAElement &
    SVGCircleElement &
    SVGClipPathElement &
    SVGDefsElement &
    SVGDescElement &
    SVGEllipseElement &
    SVGFEBlendElement &
    SVGFEColorMatrixElement &
    SVGFEComponentTransferElement &
    SVGFECompositeElement &
    SVGFEConvolveMatrixElement &
    SVGFEDiffuseLightingElement &
    SVGFEDisplacementMapElement &
    SVGFEDistantLightElement &
    SVGFEFloodElement &
    SVGFEFuncAElement &
    SVGFEFuncBElement &
    SVGFEFuncGElement &
    SVGFEFuncRElement &
    SVGFEGaussianBlurElement &
    SVGFEImageElement &
    SVGFEMergeElement &
    SVGFEMergeNodeElement &
    SVGFEMorphologyElement &
    SVGFEOffsetElement &
    SVGFEPointLightElement &
    SVGFESpecularLightingElement &
    SVGFESpotLightElement &
    SVGFETileElement &
    SVGFETurbulenceElement &
    SVGFilterElement &
    SVGForeignObjectElement &
    SVGGElement &
    SVGImageElement &
    SVGLineElement &
    SVGLinearGradientElement &
    SVGMarkerElement &
    SVGMaskElement &
    SVGMetadataElement &
    SVGPathElement &
    SVGPatternElement &
    SVGPolygonElement &
    SVGPolylineElement &
    SVGRadialGradientElement &
    SVGRectElement &
    SVGScriptElement &
    SVGStopElement &
    SVGStyleElement &
    SVGSVGElement &
    SVGSwitchElement &
    SVGSymbolElement &
    SVGTextElement &
    SVGTextPathElement &
    SVGTitleElement &
    SVGTSpanElement &
    SVGUseElement &
    SVGViewElement &
    DocumentFragment;
  interface IntrinsicElements {
    [elemName: string]: unknown;
    span: Partial<HTMLSpanElement>;
    a: Partial<HTMLAnchorElement>;
  }
}
