/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconMdiAlertDecagramOutline: typeof import('~icons/mdi/alert-decagram-outline.vue')['default']
    IconMdiChartBar: typeof import('~icons/mdi/chart-bar.vue')['default']
    IconMdiEyeOff: typeof import('~icons/mdi/eye-off.vue')['default']
    IconMdiFileChart: typeof import('~icons/mdi/file-chart.vue')['default']
    IconMdiInformation: typeof import('~icons/mdi/information.vue')['default']
    IconMdiPalette: typeof import('~icons/mdi/palette.vue')['default']
    Label: typeof import('radix-vue')['Label']
  }
}
