/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconMdiAlertDecagramOutline: typeof import('~icons/mdi/alert-decagram-outline.vue')['default']
    IconMdiChartBar: typeof import('~icons/mdi/chart-bar.vue')['default']
    IconMdiEyeOff: typeof import('~icons/mdi/eye-off.vue')['default']
    IconMdiFileChart: typeof import('~icons/mdi/file-chart.vue')['default']
    IconMdiInformation: typeof import('~icons/mdi/information.vue')['default']
    IconMdiLightbulbOn: typeof import('~icons/mdi/lightbulb-on.vue')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent.vue')['default']
    IconMdiPalette: typeof import('~icons/mdi/palette.vue')['default']
    OptionCategory: typeof import('./options_ui/components/OptionCategory.vue')['default']
    OptionNote: typeof import('./options_ui/components/OptionNote.vue')['default']
    OptionRow: typeof import('./options_ui/components/OptionRow.vue')['default']
    OptionsReadingSpeed: typeof import('./options_ui/components/OptionsReadingSpeed.vue')['default']
    OptionsUIHeader: typeof import('./options_ui/components/OptionsUIHeader.vue')['default']
    OptionSwitch: typeof import('./options_ui/components/OptionSwitch.vue')['default']
    OptionTheme: typeof import('./options_ui/components/OptionTheme.vue')['default']
    OptionThemeItem: typeof import('./options_ui/components/OptionThemeItem.vue')['default']
    RadixLabel: typeof import('radix-vue')['Label']
    RadixRadioGroupItem: typeof import('radix-vue')['RadioGroupItem']
    RadixRadioGroupRoot: typeof import('radix-vue')['RadioGroupRoot']
    RadixSliderRange: typeof import('radix-vue')['SliderRange']
    RadixSliderRoot: typeof import('radix-vue')['SliderRoot']
    RadixSliderThumb: typeof import('radix-vue')['SliderThumb']
    RadixSliderTrack: typeof import('radix-vue')['SliderTrack']
    RadixSwitchRoot: typeof import('radix-vue')['SwitchRoot']
    RadixSwitchThumb: typeof import('radix-vue')['SwitchThumb']
    RadixTooltipContent: typeof import('radix-vue')['TooltipContent']
    RadixTooltipPortal: typeof import('radix-vue')['TooltipPortal']
    RadixTooltipProvider: typeof import('radix-vue')['TooltipProvider']
    RadixTooltipRoot: typeof import('radix-vue')['TooltipRoot']
    RadixTooltipTrigger: typeof import('radix-vue')['TooltipTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sonner: typeof import('./options_ui/components/Sonner.vue')['default']
    Tooltip: typeof import('./options_ui/components/basic/Tooltip.vue')['default']
  }
}
